trigger:
- main
- feature-azure-pipelines

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.14.1'
      installKubectl: true


  - script: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

