trigger:
- main
- feature-*

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: build
  displayName: 'Build'
  steps:
  - script: chmod 777 gradlew; ./gradlew test

- job: sonar
  workspace:
    clean: all
  displayName:  Code Review
  steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'Sonarcloud'
      organization: 'devops-foundation'
      projectKey: 'DevOps-Foundation_Microservicio-spring'
      projectName: 'testing-web'
    displayName: 'Preparing Sonarqube Environment'
    
  - task: Gradle@3
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: "sonarqube"
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: true
      sqGradlePluginVersionChoice: 'specify'
      sonarQubeGradlePluginVersion: '3.3'
    displayName: 'Analyze current Branch'
    
  - task: SonarCloudPublish@1
    inputs:
      pollingTimeoutSec: '300'
    displayName: 'Publish Analysis Results'

- job: buildimage
  displayName:  Construccion Imagen
  steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'Docker-registry'
      repository: 'microservicio-spring'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'


