resources:
  repositories:
    - repository: configmap-repo-dsr
      type: github
      name: DevOps-Foundation/Selenium
      endpoint: DevOps-Foundation
      ref: main

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: PerformanceTest
  steps:
  - script: |
      git config --global user.name "clagosu"
      git config --global user.email clagos353@gmail.com
      git clone https://github.com/DevOps-Foundation/Selenium.git
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'Selenium/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
