resources:
  repositories:
    - repository: configmap-repo-dsr
      type: github
      name: DevOps-Foundation/Selenium
      endpoint: DevOps-Foundation
      ref: main

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: PerformanceTest
  steps:
  - script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --global user.name "clagosu"
      git config --global user.email clagos353@gmail.com
      ssh-keyscan -t rsa "github.com" >> ~/.ssh/known_hosts
      git clone git@github.com:DevOps-Foundation/Selenium.git
  
  - task: Maven@3
    inputs:
      mavenPomFile: 'Selenium/pom.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false
