trigger:
- main
- feature-azure-pipelines

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: HelmInstaller@0
    inputs:
      helmVersion: '2.14.1'
      installKubectl: true
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'Azure-k8s'
      command: 'login'
  - script: kubectl port-forward --namespace monitoring svc/prometheus-grafana 8090:80

  #- script: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  #- task: HelmDeploy@0
    #inputs:
      #connectionType: 'Azure Resource Manager'
      #azureSubscription: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
      #azureResourceGroup: 'aks-getting-started'
      #kubernetesCluster: 'aks-getting-started'
      #namespace: 'monitoring'
      #command: 'install'
      #chartType: 'Name'
      #chartName: 'prometheus-community/kube-prometheus-stack'
      #arguments: '-n monitoring'
    
  
