trigger:
- main
- feature-azure-pipelines

pool:
  vmImage: ubuntu-latest
  
jobs:
- job: build
  displayName: 'Build'
  steps:
  - task: Kubernetes@1
    inputs:
      connectionType: 'Azure Resource Manager'
      azureSubscriptionEndpoint: 'azure(9909fced-8203-44b6-af68-11f833a37e60)'
      azureResourceGroup: 'aks-getting-started'
      kubernetesCluster: 'aks-getting-started'
      command: 'get'
      arguments: 'deployments hello-world'
      secretType: 'dockerRegistry'
      containerRegistryType: 'Azure Container Registry'


