apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-spring
  template:
    metadata:
      labels:
        app: ms-spring
    spec:
      containers:
      - name: nginx
        image: clagos/microservicio-spring:latest
        ports:
        - containerPort: 8080