apiVersion: v1
kind: Pod
metadata:
  name: ms-spring
spec:
  containers:
    - name: ms-spring
      image: clagosu/microservicio-spring
      imagePullSecrets: az-k8s-secret
      ports:
       - containerPort: 8080
